### ISSUE TITLE
Open 2nd write tx: fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by jeffkayser2** [coreos/bbolt#69]
```go
package main

import (
        "os"
        "fmt"
        bolt "github.com/coreos/bbolt"
)

func main() {
        var err error
        err = doWork()
        if err != nil {
                fmt.Fprintf(os.Stderr, "%s\n", err.Error())
                os.Exit(1)
        }
        os.Exit(0)
}

func pe(err error) string {
        if err != nil {
                return err.Error()
        }
        return "nil"
}

func doWork() error {
        db, err := bolt.Open("test.db", 0600, nil)
        fmt.Fprintf( os.Stderr, "open db: %s\n", pe(err))
        defer db.Close()

        tx1, err := db.Begin(true)
        fmt.Fprintf( os.Stderr, "01: tx 1: start rw: %s\n", pe(err))
        tx2, err := db.Begin(true)
        fmt.Fprintf( os.Stderr, "02: tx 2: start rw: %s\n", pe(err))
}
```

```
[jkayser@oel7latest cryptstore]$ bin/bolttest1
open db: nil
01: tx 1: start rw: nil
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc42006618c, 0x48e400)
        /usr/local/go1.9.2/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420066188)
        /usr/local/go1.9.2/src/sync/mutex.go:134 +0xee
github.com/coreos/bbolt.(*DB).beginRWTx(0xc420066000, 0x0, 0x0, 0x0)
        /home/jkayser/projects/jkayser/experiment/cryptstore/src/github.com/coreos/bbolt/db.go:566 +0x65
github.com/coreos/bbolt.(*DB).Begin(0xc420066000, 0xc42000c001, 0x4e9518, 0x17, 0xc420041ed0)
        /home/jkayser/projects/jkayser/experiment/cryptstore/src/github.com/coreos/bbolt/db.go:515 +0x38
main.doWork(0x0, 0x0)
        /home/jkayser/projects/jibe/general/cryptstore/src/cmd/bolttest1/bolttest1.go:37 +0x271
main.main()
        /home/jkayser/projects/jibe/general/cryptstore/src/cmd/bolttest1/bolttest1.go:14 +0x26
[jkayser@oel7latest cryptstore]$
```

**Comment by xiang90** [comment]
can you format your code to make it readable?

**Comment by IaBurton** [comment]
The documentation mentions write transactions blocking
https://godoc.org/github.com/coreos/bbolt#DB.Begin

Meaning if you attempt to open more than one in the same goroutine it will deadlock, and since you only have the "main" goroutine in your example program Go's runtime detects all goroutines as asleep and dies.

**Comment by xiang90** [comment]
closing this issue. what @IaBurton said is correct.
